on: push
jobs:
  lint:
    uses: internetarchive/dyno/.github/workflows/lint.yml@main

  test:
    runs-on: self-hosted
    container:
      # https://github.com/internetarchive/dyno
      image: ghcr.io/internetarchive/dyno:main
    steps:
    - uses: actions/checkout@v4
    - run: /app/test/test.sh

  cicd:
    runs-on: self-hosted
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
    needs: [lint, test]

  image-test:
    runs-on: self-hosted
    needs: [cicd]
    container:
      # test using the just built-and-pushed docker image from the [cicd] job above
      image: 'docker://ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
    steps:
    - run: fgrep 'hello js' /app/index.js
